version: '2'
services:

    nginx:
        container_name: nginx
        image: nginx:1.17
        restart: always
        ports:
            - "9999:9999"
        volumes:
            - ../:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
    php:
        container_name: php
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ../:/var/www
            - ./php-config/php.ini:/usr/local/etc/php/php.ini

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_HOST=mysql
            - PMA_PORT=3306
        ports:
            - 8000:80
        volumes:
            - /sessions


